// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPal.Auth.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyPal.Auth.Data.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260802175315_InitialAuthSchema")]
    partial class InitialAuthSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyPal.Auth.Data.Entities.LifeTrackHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventTriggerType")
                        .HasColumnType("text")
                        .HasColumnName("event_trigger_type");

                    b.Property<string>("PreviousStory")
                        .HasColumnType("text")
                        .HasColumnName("previous_story");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("life_track_history", "public");
                });

            modelBuilder.Entity("MyPal.Auth.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("GooglePlaceId")
                        .HasColumnType("text")
                        .HasColumnName("google_place_id");

                    b.Property<bool>("IsBuyer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_buyer");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSeller")
                        .HasColumnType("boolean")
                        .HasColumnName("is_seller");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<double?>("Lat")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric")
                        .HasColumnName("lat");

                    b.Property<string>("LifeTrackStory")
                        .HasColumnType("text")
                        .HasColumnName("life_track_story");

                    b.Property<double?>("Lng")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric")
                        .HasColumnName("lng");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.PrimitiveCollection<string[]>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("roles");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_users_email");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("MyPal.Auth.Data.Entities.UserAlgorithmSteering", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("SectorName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sector_name");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<double>("WeightMultiplier")
                        .HasColumnType("numeric")
                        .HasColumnName("weight_multiplier");

                    b.HasKey("UserId", "SectorName");

                    b.ToTable("user_algorithm_steering", "public");
                });

            modelBuilder.Entity("MyPal.Auth.Data.Entities.LifeTrackHistory", b =>
                {
                    b.HasOne("MyPal.Auth.Data.Entities.User", "User")
                        .WithMany("LifeTrackHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyPal.Auth.Data.Entities.UserAlgorithmSteering", b =>
                {
                    b.HasOne("MyPal.Auth.Data.Entities.User", "User")
                        .WithMany("AlgorithmSteerings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyPal.Auth.Data.Entities.User", b =>
                {
                    b.Navigation("AlgorithmSteerings");

                    b.Navigation("LifeTrackHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
